source 'https://rubygems.org'

gem 'rails', '3.2.3'
gem 'rack-oauth2', '1.0.5'
gem 'bootstrap-sass', '2.0.0'
gem 'rest-client', '>=1.6.7'
gem 'multipart-post'
gem 'google-api-client'
gem 'aws-flow'
gem 'integration-demos-lib', '1.0.0'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

group :development, :test do
	gem 'rspec-rails', '2.9.0'
	gem 'guard-rspec', '0.5.5'
    gem 'sqlite3', '1.3.5'
end

group :production do
  gem 'mysql2'
end


# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '3.2.4'
  gem 'coffee-rails', '3.2.2'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer', :platforms => :ruby

  gem 'uglifier', '1.2.3'
end

gem 'jquery-rails', '2.2.1'

group :test do
	gem 'rspec-rails', '2.9.0'
	gem 'capybara', '1.1.2'
	gem 'growl', '1.0.3'
	gem 'guard-spork', '0.3.2'
	gem 'spork', '0.9.0'
end

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'debugger